package homework;

import java.awt.Point;

/**
 * Represents a seed generated by clicking within a VoronoiComponent. A seed stores
 * accompanying data including the Ellipse2D.Double to be drawn in its place, the point at
 * its center, and the color of its surrounding Voronoi cell.
 * @author John Gibson
 */
public class Seed {
    
    private final Point point;
    private final Ellipse2D.Double circle;
    private Color cellColor;
    
    public Seed(Point point, double radius, Color c) {
        this.point = point;
        circle = new Ellipse2D.Double(point.x - radius, point.y - radius, 
            2 * radius, 2 * radius);
        this.cellColor = c;
    }
    
    public Ellipse2D.Double getCircle() {
        return circle;
    }
    
    public Color getColor() {
        return cellColor;
    }
    
    public Point getPoint() {
        return point;
    }
    
    public void setColor(Color c) {
        cellColor = c;
    }
    
    @Override
    public String toString() {
        return "[" + point.getX() + ", " + point.getY() + "]";
    }
    
}
